# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/ZYBO_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: ip/mem2p_76800_12/mem2p_76800_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem2p_76800_12 || ORIG_REF_NAME==mem2p_76800_12}]

# IP: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/mem2p_76800_24/ip/mem2p_76800_24/mem2p_76800_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem2p_76800_24 || ORIG_REF_NAME==mem2p_76800_24}]

# IP: ip/F_3/F_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==F_3 || ORIG_REF_NAME==F_3}]

# IP: ip/F_2/F_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==F_2 || ORIG_REF_NAME==F_2}]

# IP: ip/F_1/F_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==F_1 || ORIG_REF_NAME==F_1}]

# IP: ip/B_3/B_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_3 || ORIG_REF_NAME==B_3}]

# IP: ip/B_2/B_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_2 || ORIG_REF_NAME==B_2}]

# IP: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.srcs/sources_1/ip/B_1/B_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==B_1 || ORIG_REF_NAME==B_1}]

# XDC: bd/design_1/design_1_ooc.xdc
