directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:if:acc#8 RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#4:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J#1:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#3:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#3:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J#2:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:oelse:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:oelse:acc#2 RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:oelse:acc RESOURCE_NAME BIAS_I#1:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#7 RESOURCE_NAME FOR_A#1:if:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#7 RESOURCE_NAME FOR_A#1:if:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc RESOURCE_NAME FOR_A#1:if:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:acc#6 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:acc#3 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#1:acc#2 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:acc#6 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:acc#3 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#3:acc#2 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:acc#6 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#5:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#5:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:acc#3 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#5:acc#2 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#2:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#4:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#5:acc#2 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#5:acc#2 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#6:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#6:acc#1 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc#9 RESOURCE_NAME FOR_A#1:acc#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:if:acc#6 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#15 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#15 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#18 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#5:if:acc#6 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc#12 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:if:acc#10 RESOURCE_NAME FOR_A#1:if:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#9 RESOURCE_NAME FOR_A#1:if:acc#9:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:if:acc#7 RESOURCE_NAME FOR_A#1:if:acc#9:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#9 RESOURCE_NAME FOR_A#1:if:acc#9:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#10 RESOURCE_NAME FOR_A#1:if:acc#9:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#5:if:acc#4 RESOURCE_NAME FOR_A#1:if:acc#9:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#1:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#1:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#1:acc#2 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#1:acc#2 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J#1:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc#4 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#2:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#7 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J#1:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#10 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/for:acc#2 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#7:acc#1 RESOURCE_NAME BIAS_I#1:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#3:acc#1 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#3:acc#1 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#3:acc#2 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#3:acc#2 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J#2:acc#1 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#2:acc#4 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#4:acc#1 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#7 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J#2:acc#1 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#10 RESOURCE_NAME BIAS_I#2:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:if:acc#8 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#8 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#11 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#15 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_L#2:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_L#2:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#5:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/for:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J#7:acc RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc#8 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#14 RESOURCE_NAME BIAS_I#1:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#13 RESOURCE_NAME BIAS_I#1:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#1:if:acc#4 RESOURCE_NAME BIAS_I#1:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc#5 RESOURCE_NAME BIAS_I#1:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#8 RESOURCE_NAME BIAS_I#1:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#12 RESOURCE_NAME BIAS_I#1:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_J:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I:acc#4 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_J:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc#7 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_J:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc#10 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_L#2:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_L#2:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#5:acc#1 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc#8 RESOURCE_NAME BIAS_I:acc#10:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I:acc#7 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc#10 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc#14 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc#6 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#9 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#13 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#11 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#3:if:acc#3 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:if:acc#13 RESOURCE_NAME BIAS_I#1:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:if:acc#7 RESOURCE_NAME FOR_B#4:if:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc#11 RESOURCE_NAME FOR_B#4:if:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I:acc#5 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc#8 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc#12 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#11 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#15 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#17 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#2:acc#8 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#6:acc#13 RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#5:if:acc RESOURCE_NAME BIAS_I#2:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_L:acc#1 RESOURCE_NAME FOR_K#1:acc#1:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_L:acc#1 RESOURCE_NAME FOR_K#1:acc#1:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#1:acc#1 RESOURCE_NAME FOR_K#1:acc#1:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#2:acc#1 RESOURCE_NAME FOR_K#1:acc#1:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:acc#7 RESOURCE_NAME FOR_B#2:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:acc#7 RESOURCE_NAME FOR_B#2:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:acc RESOURCE_NAME FOR_B#2:acc#7:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:acc RESOURCE_NAME FOR_B#2:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:acc RESOURCE_NAME FOR_B#2:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:acc#7 RESOURCE_NAME FOR_B#2:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:acc#3 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_L#1:acc#1 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:if:acc#6 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_L#1:acc#1 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#3:acc#1 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#4:acc#1 RESOURCE_NAME FOR_B#2:if:acc#6:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:if:acc#11 RESOURCE_NAME BIAS_I:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc#11 RESOURCE_NAME BIAS_I:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc#15 RESOURCE_NAME BIAS_I:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I:acc#8 RESOURCE_NAME BIAS_I:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#14 RESOURCE_NAME BIAS_I:acc#15:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B:if:mul#4 RESOURCE_NAME FOR_B#2:if:mul#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:if:mul#3 RESOURCE_NAME FOR_B#2:if:mul#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:if:mul#5 RESOURCE_NAME FOR_B#2:if:mul#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_K#7:mul#1 RESOURCE_NAME FOR_B#2:if:mul#3:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:asn(CR1_simple:add_AF(10:FOR_I:acc RESOURCE_NAME BIAS_I:asn(CR1_simple:add_AF(10:BIAS_I:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:asn(CR1_simple:add_AF(10:BIAS_I:acc RESOURCE_NAME BIAS_I:asn(CR1_simple:add_AF(10:BIAS_I:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#9 RESOURCE_NAME BIAS_I#2:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#13 RESOURCE_NAME BIAS_I#2:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#13 RESOURCE_NAME FOR_A#5:if:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#5:if:acc#7 RESOURCE_NAME FOR_A#5:if:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I:acc#2 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I:acc#11 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc#4 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#2 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#11 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#4 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:oelse#2:acc RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#2 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#11 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#4 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/for:acc#1 RESOURCE_NAME BIAS_I#1:acc#11:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#1:if:acc RESOURCE_NAME BIAS_I#1:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#1:if:acc RESOURCE_NAME BIAS_I#1:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#1:acc#7 RESOURCE_NAME BIAS_I#1:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#2:acc#10 RESOURCE_NAME BIAS_I#1:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#1:acc#14 RESOURCE_NAME BIAS_I#1:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#2:if:acc RESOURCE_NAME FOR_B#2:if:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#4:if:acc RESOURCE_NAME FOR_B#2:if:acc:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#3:if:acc#13 RESOURCE_NAME FOR_A#3:if:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_A#5:if:acc#16 RESOURCE_NAME FOR_A#3:if:acc#13:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_B#3:if:acc RESOURCE_NAME BIAS_I#2:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#2:acc#7 RESOURCE_NAME BIAS_I#2:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#10 RESOURCE_NAME BIAS_I#2:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#14 RESOURCE_NAME BIAS_I#2:acc#14:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/INIT_I#2:acc#5 RESOURCE_NAME BIAS_I#2:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/FOR_I#4:acc#8 RESOURCE_NAME BIAS_I#2:acc#12:rg
directive set /CNN_main_simple/CNN_main_simple:core/CNN_main_simple:core:conc/BIAS_I#2:acc#12 RESOURCE_NAME BIAS_I#2:acc#12:rg
