# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.xci
# IP: The module: 'image_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.xci
# IP: The module: 'image_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
