# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config  -ruleid {1}  -id {Labtoolstcl 44-513}  -suppress 
set_msg_config  -ruleid {2}  -id {Synth 37-1}  -suppress 
set_msg_config  -ruleid {3}  -id {Synth 37-3}  -suppress 
set_msg_config  -ruleid {4}  -id {Netlist 29-77}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboAudio/ZyboRTOS/ip_repo
  /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ip_repo
} [current_project]
set_property ip_output_repo /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.xci
set_property used_in_implementation false [get_files -all /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_ooc.xdc]
set_property is_locked true [get_files /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1 -new_name image_in -ip [get_ips image_in]]

if { $cached_ip eq {} } {

synth_design -top image_in -part xc7z010clg400-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix image_in_ image_in.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ image_in_stub.v
 lappend ipCachedFiles image_in_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ image_in_stub.vhdl
 lappend ipCachedFiles image_in_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ image_in_sim_netlist.v
 lappend ipCachedFiles image_in_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ image_in_sim_netlist.vhdl
 lappend ipCachedFiles image_in_sim_netlist.vhdl

 config_ip_cache -add -dcp image_in.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips image_in]
}

rename_ref -prefix_all image_in_

write_checkpoint -force -noxdef image_in.dcp

catch { report_utilization -file image_in_utilization_synth.rpt -pb image_in_utilization_synth.pb }

if { [catch {
  file copy -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in.dcp /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in.dcp /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in_stub.v /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in_stub.vhdl /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in_sim_netlist.v /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/bitstream/image_in_synth_1/image_in_sim_netlist.vhdl /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.ip_user_files/ip/image_in]} {
  catch { 
    file copy -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.v /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.ip_user_files/ip/image_in
  }
}

if {[file isdir /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.ip_user_files/ip/image_in]} {
  catch { 
    file copy -force /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/project_1/project_1.srcs/sources_1/ip/image_in/image_in_stub.vhdl /tp-fmr/xph3sei710_Tamancoldi_Silveira/Vivado/CNN_CIFAR10/Zynq/Zybo/ZyboTest/ZyboCAMVGAProc/ZyboCAMVGAProc.ip_user_files/ip/image_in
  }
}
