// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2011a.62 Production Release
//  HLS Date:       Wed Nov 23 15:08:20 PST 2011
// 
//  Generated by:   xph3seiaba@cimeld20
//  Generated date: Fri Oct 24 14:34:32 2014
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    lab1_core
// ------------------------------------------------------------------


module lab1_core (
  clk, rst, a_rsc_mgc_in_wire_d, b_rsc_mgc_in_wire_d, c_rsc_mgc_out_stdreg_d
);
  input clk;
  input rst;
  input [255:0] a_rsc_mgc_in_wire_d;
  input [255:0] b_rsc_mgc_in_wire_d;
  output [255:0] c_rsc_mgc_out_stdreg_d;
  reg [255:0] c_rsc_mgc_out_stdreg_d;


  always begin : core
    // Interconnect Declarations
    reg [255:0] ACC_io_read_a_rsc_d_cse_sva;
    reg [255:0] ACC_io_read_b_rsc_d_cse_sva;

    begin : mainExit
      forever begin : main
        // C-Step 0 of Loop 'main'
        begin : waitLoop0Exit
          forever begin : waitLoop0
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop0Exit;
          end
        end
        // C-Step 1 of Loop 'main'
        ACC_io_read_a_rsc_d_cse_sva = a_rsc_mgc_in_wire_d;
        ACC_io_read_b_rsc_d_cse_sva = b_rsc_mgc_in_wire_d;
        c_rsc_mgc_out_stdreg_d <= {((ACC_io_read_a_rsc_d_cse_sva[255:224]) + (ACC_io_read_b_rsc_d_cse_sva[255:224]))
            , ((ACC_io_read_a_rsc_d_cse_sva[223:192]) + (ACC_io_read_b_rsc_d_cse_sva[223:192]))
            , ((ACC_io_read_a_rsc_d_cse_sva[191:160]) + (ACC_io_read_b_rsc_d_cse_sva[191:160]))
            , ((ACC_io_read_a_rsc_d_cse_sva[159:128]) + (ACC_io_read_b_rsc_d_cse_sva[159:128]))
            , ((ACC_io_read_a_rsc_d_cse_sva[127:96]) + (ACC_io_read_b_rsc_d_cse_sva[127:96]))
            , ((ACC_io_read_a_rsc_d_cse_sva[95:64]) + (ACC_io_read_b_rsc_d_cse_sva[95:64]))
            , ((ACC_io_read_a_rsc_d_cse_sva[63:32]) + (ACC_io_read_b_rsc_d_cse_sva[63:32]))
            , ((ACC_io_read_a_rsc_d_cse_sva[31:0]) + (ACC_io_read_b_rsc_d_cse_sva[31:0]))};
        begin : waitLoop1Exit
          forever begin : waitLoop1
            @(posedge clk);
            if ( rst )
              disable mainExit;
            if ( clk )
              disable waitLoop1Exit;
          end
        end
        // C-Step 2 of Loop 'main'
      end
    end
    ACC_io_read_b_rsc_d_cse_sva = 256'b0;
    ACC_io_read_a_rsc_d_cse_sva = 256'b0;
    c_rsc_mgc_out_stdreg_d <= 256'b0;
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    lab1
//  Generated from file(s):
//    2) $PROJECT_HOME/lab1.cpp
// ------------------------------------------------------------------


module lab1 (
  a_rsc_z, b_rsc_z, c_rsc_z, clk, rst
);
  input [255:0] a_rsc_z;
  input [255:0] b_rsc_z;
  output [255:0] c_rsc_z;
  input clk;
  input rst;


  // Interconnect Declarations
  wire [255:0] a_rsc_mgc_in_wire_d;
  wire [255:0] b_rsc_mgc_in_wire_d;
  wire [255:0] c_rsc_mgc_out_stdreg_d;

  mgc_in_wire #(.rscid(1),
  .width(256)) a_rsc_mgc_in_wire (
      .d(a_rsc_mgc_in_wire_d),
      .z(a_rsc_z)
    );
  mgc_in_wire #(.rscid(2),
  .width(256)) b_rsc_mgc_in_wire (
      .d(b_rsc_mgc_in_wire_d),
      .z(b_rsc_z)
    );
  mgc_out_stdreg #(.rscid(3),
  .width(256)) c_rsc_mgc_out_stdreg (
      .d(c_rsc_mgc_out_stdreg_d),
      .z(c_rsc_z)
    );
  lab1_core lab1_core_inst (
      .clk(clk),
      .rst(rst),
      .a_rsc_mgc_in_wire_d(a_rsc_mgc_in_wire_d),
      .b_rsc_mgc_in_wire_d(b_rsc_mgc_in_wire_d),
      .c_rsc_mgc_out_stdreg_d(c_rsc_mgc_out_stdreg_d)
    );
endmodule



