-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2011a.62 Production Release
--  HLS Date:       Wed Nov 23 15:08:20 PST 2011
-- 
--  Generated by:   xph3seiaba@cimeld20
--  Generated date: Fri Oct 24 14:34:35 2014
-- ----------------------------------------------------------------------

-- 
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
LIBRARY mgc_hls;
USE mgc_hls.funcs.ALL;

PACKAGE lab1_mux_pkg IS 
  FUNCTION MUX_v_256_2_2(inputs : STD_LOGIC_VECTOR(511 DOWNTO 0); sel : STD_LOGIC)
    RETURN STD_LOGIC_VECTOR;
END lab1_mux_pkg;

PACKAGE BODY lab1_mux_pkg IS
FUNCTION MUX_v_256_2_2(inputs : STD_LOGIC_VECTOR(511 DOWNTO 0); sel : STD_LOGIC)
RETURN STD_LOGIC_VECTOR IS
  VARIABLE or_inputs : STD_LOGIC_VECTOR(511 DOWNTO 0);
  VARIABLE result : STD_LOGIC_VECTOR(255 DOWNTO 0);
  VARIABLE tmp : STD_LOGIC_VECTOR(255 DOWNTO 0);
  VARIABLE result_new : STD_LOGIC;

  BEGIN
    CASE sel IS
      WHEN '1' =>
        result := inputs(255 DOWNTO 0);
      WHEN '0' =>
        result := inputs(511 DOWNTO 256);
      WHEN others =>
        result := (others => '0');
        -- pragma translate_off
        result_new := '1';
        FOR i IN 0 TO 1 LOOP
          IF ( result_new = '1' ) THEN
            result := inputs((i+1)*256-1 DOWNTO i*256);
            result_new := '0';
          ELSE
            result := resolve_std_logic_vector(result, inputs((i+1)*256-1 DOWNTO
                i*256));
          END IF;
        END LOOP;
        -- pragma translate_on
    END CASE;
  RETURN result;
END;

END lab1_mux_pkg;


